--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
constants: []

full_name: SOAP::HTTPConfigLoader
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: cert_from_file
- !ruby/object:RI::MethodSummary 
  name: key_from_file
- !ruby/object:RI::MethodSummary 
  name: set_basic_auth
- !ruby/object:RI::MethodSummary 
  name: set_options
- !ruby/object:RI::MethodSummary 
  name: set_ssl_config
- !ruby/object:RI::MethodSummary 
  name: ssl_config_int
name: HTTPConfigLoader
superclass: 
