--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: SOAP::HTTPConfigLoader#set_ssl_config
is_singleton: false
name: set_ssl_config
params: (client, ssl_config)
visibility: public
