--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: SOAP::HTTPConfigLoader#ssl_config_int
is_singleton: false
name: ssl_config_int
params: (value)
visibility: public
