--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: 
- !ruby/object:RI::MethodSummary 
  name: new
comment: 
constants: []

full_name: SOAP::RPC::Router::ApplicationScopeOperation
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: receiver
name: ApplicationScopeOperation
superclass: Operation
