--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Resolv::DNS::Config::default_config_hash
is_singleton: true
name: default_config_hash
params: (filename="/etc/resolv.conf")
visibility: public
