--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Resolv::DNS::Config#generate_candidates
is_singleton: false
name: generate_candidates
params: (name)
visibility: public
