--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Resolv::DNS::Config#generate_timeouts
is_singleton: false
name: generate_timeouts
params: ()
visibility: public
