--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: candidate, tout, nameserver
comment: 
full_name: Resolv::DNS::Config#resolv
is_singleton: false
name: resolv
params: (name) {|candidate, tout, nameserver| ...}
visibility: public
