--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
constants: []

full_name: Resolv::DNS::Config::OtherResolvError
includes: []

instance_methods: []

name: OtherResolvError
superclass: ResolvError
