--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
constants: []

full_name: Resolv::DNS::Config::NXDomain
includes: []

instance_methods: []

name: NXDomain
superclass: ResolvError
